# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_main_title', models.CharField(blank=True, default=0, max_length=1024)),
                ('detail_title', models.CharField(blank=True, default=0, max_length=1024)),
                ('title_status', models.CharField(blank=True, choices=[('CL', 'Clean'), ('SA', 'Salvage'), ('RE', 'Rebuilt'), ('PA', 'Parts Only'), ('LE', 'Lien'), ('MS', 'Missing')], default='', max_length=2)),
                ('v_size', models.CharField(blank=True, choices=[('CP', 'Compact'), ('FU', 'Full'), ('MS', 'Mid Size'), ('SC', 'Sub Compact')], default='', max_length=2)),
                ('fuel', models.CharField(blank=True, choices=[('GA', 'Gas'), ('DS', 'Diesel'), ('HY', 'Hybrid'), ('EL', 'Electric'), ('OT', 'Fuel Other')], default='', max_length=2)),
                ('v_type', models.CharField(blank=True, choices=[('BS', 'Bus'), ('CV', 'Convertible'), ('CP', 'Coupe'), ('HB', 'Hatchback'), ('MV', 'Mini Van'), ('OR', 'Offroad'), ('PU', 'Pickup'), ('SD', 'Sedan'), ('TK', 'Truck'), ('SU', 'SUV'), ('WG', 'Wagon')], default='', max_length=2)),
                ('condition', models.CharField(blank=True, choices=[('NE', 'New'), ('LN', 'Like New'), ('EX', 'Excellent'), ('GD', 'Good'), ('FA', 'Fair'), ('SA', 'Salvage')], default='', max_length=2)),
                ('cylinders', models.IntegerField(choices=[(3, '3 Cylinders'), (4, '4 Cylinders'), (5, '5 Cylinders'), (6, '6 Cylinders'), (8, '8 Cylinders'), (10, '10 Cylinders'), (12, '12 Cylinders'), (99, 'Other Cylinders')], default=0)),
                ('transmission', models.CharField(blank=True, choices=[('MA', 'Manual'), ('AU', 'Automatic'), ('OT', 'Other')], default='', max_length=2)),
                ('drive', models.CharField(blank=True, choices=[('FD', 'Front Wheel Drive'), ('RD', 'Rear Wheel Drive'), ('FW', 'Four Wheel Drive')], default='', max_length=2)),
                ('odometer', models.IntegerField(blank=True, default=0)),
                ('paint_color', models.CharField(blank=True, choices=[('BL', 'Black'), ('BU', 'Blue'), ('GN', 'Green'), ('GY', 'Grey'), ('OR', 'Orange'), ('PU', 'Purple'), ('RD', 'Red'), ('SL', 'Silver'), ('WH', 'White'), ('YL', 'Yellow'), ('CU', 'Custom'), ('BR', 'Brown')], default='', max_length=2)),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
                ('map_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('map_accuracy', models.IntegerField(blank=True, default=0)),
                ('address', models.CharField(blank=True, default=0, max_length=256)),
                ('pri_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField()),
                ('price', models.IntegerField(blank=True, default=0)),
                ('link', models.URLField(blank=True, max_length=1024, null=True)),
                ('key', models.CharField(blank=True, default=0, max_length=256)),
                ('VIN', models.CharField(blank=True, default=0, max_length=256)),
                ('posting_time', models.DateField()),
                ('last_seen', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('have_counted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('niceName', models.CharField(max_length=128)),
                ('edmunds_id', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MakeAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Make')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('niceName', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('trim', models.CharField(max_length=128)),
                ('edmunds_id', models.CharField(blank=True, default='', max_length=128)),
                ('edmunds_year_id', models.IntegerField(blank=True, default=0)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('avg_condition', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('avg_location_latitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
                ('avg_location_longitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('image_file', models.FileField(null=True, upload_to='cl/images/%Y/%j_%H_%M_%S')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ModelAlias'),
        ),
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Make'),
        ),
        migrations.AddField(
            model_name='model',
            name='related',
            field=models.ManyToManyField(blank=True, to='report.Model'),
        ),
        migrations.AddField(
            model_name='clpost',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.VehicleImages'),
        ),
        migrations.AddField(
            model_name='clpost',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Make'),
        ),
        migrations.AddField(
            model_name='clpost',
            name='models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Model'),
        ),
    ]
