# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelalias',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='modelalias',
            name='niceName',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='modelalias',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='modelalias',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
