# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20160630_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niceName', models.CharField(blank=True, default='', max_length=128)),
                ('trim', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='model',
            name='trim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Trim'),
        ),
    ]
