# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20160630_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='trim',
        ),
        migrations.AddField(
            model_name='trim',
            name='model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Model'),
        ),
    ]
