# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_modelalias_trim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clpost',
            name='images',
        ),
        migrations.AddField(
            model_name='vehicleimages',
            name='clpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ClPost'),
        ),
    ]
