# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20160701_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='vclass',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
