# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_model_vclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='clpost',
            name='craigslist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='make',
            name='craigslist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='make',
            name='source',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='model',
            name='craigslist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='source',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='modelalias',
            name='craigslist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelalias',
            name='source',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='trim',
            name='craigslist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trim',
            name='source',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=3),
        ),
    ]
