# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20160708_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='trim',
            name='avg_condition',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trim',
            name='avg_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trim',
            name='avg_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trim',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='trim',
            name='cylinders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trim',
            name='displacement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='trim',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trim',
            name='engine',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trim',
            name='transmission',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trim',
            name='vclass',
            field=models.CharField(blank=True, choices=[('EDM', 'Edmunds API'), ('GHB', 'Git Hub Database'), ('DOE', 'DOE Database'), ('SAE', 'SAE Database'), ('CLE', 'Craigslist Entry')], default='', max_length=64),
        ),
    ]
